version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:y4Qx4CL3X+3rrliiTSMYLMAkOdg1mFo3ik/xMDzVybQ=
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.10.36
      - DB_PORT=3307
      - DB_DATABASE=db_tna
      - DB_USERNAME=root
      - DB_PASSWORD=Admin9090!
    depends_on: []
