<?php

return [
    'referensi_indikator_kinerja' => 'Isi kolom ini dengan indikator kinerja utama yang diharapkan tercapai pada tahun 2025 sebagai hasil dari pembelajaran yang diusulkan. Kolom ini juga bersifat sementara menunggu kesiapan API indikato kinerjar 2025 dari aplikasi E-SAKIP. Jika sudah tersedia di E-SAKIP maka kolom ini akan dinonaktifkan. Contoh: “Peningkatan nilai koreksi PNBP sebesar 10% setelah pelaksanaan pelatihan, dengan target nilai koreksi meningkat dari Rp50 miliar menjadi Rp55 miliar pada tahun 2025.',
    'judul' => 'Isi kolom ini dengan judul pembelajaran sesuai dengan program pembelajaran yang dipilih. Judul pembelajaran ini memuat nama program pembelajaran dan informasi tambahan seperti tahun, batch, peserta, dan lain-lain. Contoh: “Pelatihan Audit Penerimaan Negara Bukan Pajak (PNBP) bagi Pegawai di Lingkungan BPKP Batch 1 Tahun 2024”.',
    'arahan_pimpinan' => 'Isi kolom ini dengan arahan atau instruksi yang telah diberikan oleh pimpinan terkait program pembelajaran yang diusulkan. Arahan ini bisa berupa fokus utama pembelajaran, tujuan yang ingin dicapai, strategi yang harus diikuti, atau prioritas yang harus diperhatikan agar program ini selaras dengan kebijakan dan visi organisasi. Jika ada instruksi spesifik terkait metode pelatihan atau materi yang harus disertakan, tuliskan secara jelas di kolom ini. Contoh: “Pimpinan mengarahkan agar program pembelajaran ini difokuskan pada peningkatan keterampilan audit PNBP, dengan target agar auditor mampu mengidentifikasi potensi koreksi lebih besar dalam penerimaan negara. Pelatihan harus mencakup studi kasus nyata yang dapat diterapkan secara langsung dalam praktik audit.”',
    'tujuan_program_pembelajaran' => 'Isi kolom ini dengan kompetensi dasar ingin dicapai melalui program pembelajaran. Kompetensi dasar adalah pengetahuan, keterampilan, dan sikap yang minimal harus dikuasai oleh peserta pembelajaran untuk menunjukkan bahwa peserta tersebut telah menguasai standar kompetensi dan materi pelajaran. Contoh: “Meningkatkan kemampuan auditor dalam mencari, mengumpulkan, mengolah data dan/atau keterangan lainnya dalam rangka pengawasan atas kepatuhan pemenuhan kewajiban PNBP berdasarkan peraturan perundang-undangan di bidang PNBP dilaksanakan sesuai dengan ketentuan yang berlaku, sehingga mampu meningkatkan nilai koreksi PNBP sebesar 10% pada audit yang dilakukan di tahun 2025.”',
    'indikator_dampak_terhadap_kinerja_organisasi' => 'Isi kolom ini dengan indikator yang digunakan untuk mengukur dampak dari program pembelajaran terhadap kinerja organisasi secara keseluruhan. Indikator ini harus mencerminkan perubahan yang signifikan dalam hasil kinerja, efisiensi operasional, atau pencapaian tujuan strategis organisasi setelah pelaksanaan program. Contoh: “Peningkatan penerimaan negara dari PNBP sebesar 15% pada tahun 2025, yang diukur berdasarkan laporan keuangan tahunan setelah pelaksanaan pelatihan.”',
    'penugasan_yang_terkait_dengan_pembelajaran' => ' Isi kolom ini dengan penugasan atau tugas yang akan diberikan kepada peserta setelah mengikuti program pembelajaran. Penugasan ini harus dirancang untuk menerapkan pengetahuan dan keterampilan yang telah diperoleh selama pelatihan, serta mendukung pencapaian tujuan pembelajaran. Contoh: “Peserta diwajibkan untuk melakukan audit PNBP di unit kerja masing-masing dalam waktu paling lama tiga bulan setelah pelatihan, dengan fokus pada identifikasi potensi koreksi dan penyusunan laporan audit yang lengkap. Laporan tersebut harus disampaikan kepada pimpinan unit dan digunakan sebagai bahan evaluasi kinerja.',
    'skill_group_owner' => 'Isi kolom ini dengan Skill Group Owner (SGO) dari pembelajaran yang diusulkan. SGO adalah Pemilik Rumpun Keahlian adalah pejabat dan/atau pegawai yang ditunjuk oleh Penanggung Jawab Akademi berdasarkan keahlian dan penguasaan kompetensi yang dimilikinya, sesuai dengan lingkup Akademi. Contoh: Koordinator Pengawasan Bidang Pengelolaan Energi dan Sumber Daya Alam, Akademi Perekonomian dan Kemaritiman.',
    'detail_lokasi' => 'Isi kolom ini dengan informasi lengkap mengenai lokasi pelaksanaan program pembelajaran. Informasi yang perlu dicantumkan meliputi nama tempat, alamat lengkap, dan fasilitas yang tersedia di lokasi tersebut. Contoh: “Nama Tempat: Pusdiklatwas BPKP, Alamat: Jl. Jenderal Gatot Subroto No. 31, Jakarta 12950. Fasilitas: Ruang kelas dengan kapasitas 30 orang, proyektor, sound system, dan akses Wi-Fi. Kampus juga dilengkapi dengan sarana dan prasarana olahraga, tempat ibadah, klinik, dan fasilitas lainnya.”',
    'kelas' => 'Isi kolom ini dengan informasi jumlah kelas yang dibutuhkan untuk melaksanakan pembelajaran tersebut. Contoh: 2 kelas.',
    'sasaran_peserta' => 'Isi kolom ini dengan informasi mengenai siapa saja yang menjadi sasaran atau target peserta dari program pembelajaran yang diusulkan. Keterangan ini harus mencakup jabatan, unit kerja, atau kelompok pegawai yang diharapkan mengikuti pelatihan. Contoh: Auditor dengan peran sebagai ketua tim dan/atau anggota tim pada seluruh perwakilan BPKP.',
    'kriteria_peserta' => 'Isi kolom ini dengan kriteria/syarat elibilitas yang harus dipenuhi oleh peserta untuk mengikuti program pembelajaran yang diusulkan. Contoh: “Memiliki kemampuan dasar tentang PNBP; menguasai microsoft excel tingkat intermediate.”',
    'aktivitas_prapembelajaran' => 'Isi kolom ini dengan kegiatan atau tugas yang perlu dilakukan sebelum program pembelajaran dilaksanakan. Aktivitas prapembelajaran bertujuan untuk mempersiapkan peserta agar siap mengikuti pelatihan secara efektif. Kegiatan ini dapat mencakup studi literatur, pengisian kuisioner, persiapan materi, atau diskusi kelompok untuk membangun pemahaman awal tentang topik yang akan dibahas. Contoh: “Membaca dan mempelajari materi pendahuluan mengenai audit PNBP (dikirim melalui email).”',
    'sertifikat' => 'Isi kolom ini dengan informasi mengenai sertifikat yang akan diberikan kepada peserta setelah mengikuti program pembelajaran. Sertifikat ini dapat mencakup jenis sertifikat (misalnya, sertifikat mengikuti pelatihan, sertifikat kompetensi), kriteria untuk memperoleh sertifikat, serta detail tentang lembaga atau pihak yang menerbitkan sertifikat tersebut. Contoh:  Jenis Sertifikat: Sertifikat Mengikuti Pelatihan. Kriteria: Peserta harus mengikuti minimal 90% dari total sesi pelatihan dan menyelesaikan post-test dengan nilai minimal 70. Penerbit: Pusdiklatwas BPKP"',
];
